version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/src/static/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/src/tibiamapping/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/src/validation/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
